apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-web
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/azizkhanp/argoCD.git
    targetRevision: HEAD
    path: environments/staging/my-app
  destination:
    server: https://34.125.105.180
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
