apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-web
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/azizkhanp/argoCD.git
    targetRevision: HEAD
    path: my-app
  destination:
    server: https://34.125.105.180
  
